version: "0.5"

processes:
  postgres:
    command: |
      if ! podman container exists drizzle-postgres; then
        echo "Creating new container..."
        podman create \
        --name drizzle-postgres \
        -e POSTGRES_PASSWORD=mypassword \
        -p 5432:5432 \
        postgres
      fi
      echo "Starting container..."
      podman start -a drizzle-postgres
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      exec:
        command: "podman exec drizzle-postgres pg_isready -U postgres"
      initial_delay_seconds: 3
      period_seconds: 3
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
    shutdown:
      command: "podman stop drizzle-postgres"
      timeout_seconds: 5

  server:
    command: "bun run dev"
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: on_failure
      max_restarts: 5
    readiness_probe:
      http_get:
        host: localhost
        port: 5173
        path: /health
      initial_delay_seconds: 3
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

  db-push:
    command: "bun run db:push"
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: "no"
    disabled: true

  # db-seed:
  #   command: "bun run db:seed"
  #   depends_on:
  #     postgres:
  #       condition: process_healthy
  #   availability:
  #     restart: "no"
  #   disabled: true
  #
  # db-init-admin:
  #   command: "bun run db:init-admin"
  #   depends_on:
  #     postgres:
  #       condition: process_healthy
  #   availability:
  #     restart: "no"
  #   disabled: true

  db-studio:
    command: "bun run db:studio"
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: on_failure
    disabled: true
