"$schema" = "node_modules/wrangler/config-schema.json"
name = "thinkordive"
compatibility_date = "2026-03-19"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = true
